### ISSUE TITLE
how to call apiplatform/v2/oauth/token/mac using sandbox account

### ISSUE THREAD

**Issue by pravin271** [americanexpress/amex-api-dotnet-client-core#2]
Hi,

I want to call below api in dotnet
https://api.qasb.americanexpress.com/apiplatform/v2/oauth/token/mac

i have sent these headers parameters ( x-amex-api-key,x-amex-request-id,Content-Type,Authorization)
and in body 
grant_type=authorization_code
scope=Read
code=<Empty>
redirect_URL=<Empty>

i got a below response 
{
    "errorType": "invalid_request",
    "errorDescription": "input parameters are missing from the request",
    "errorCode": "154000",
    "moreInfo": ""
}

i have read american express documentation and it has mention code and redirect_url are required fields but i don't have these parameters value.

Please guide me if someone know about this problem

Thanks

**Comment by dvysotskiy** [comment]
Thank you for reaching out. The OAuth inputs are coordinated during the registration process for APIs that use the OAuth security model. Please let us know if you encounter any issues with the library.
